/* Shared services data (used by services page + booking flow) */
window.AJ = window.AJ || {};
window.AJ.services = [
  {
    id: 'oja-baza',
    category: 'oja',
    index: '01',
    title: 'Ojă semipermanentă — bază',
    shortTitle: 'Ojă semipermanentă (milky/nude)',
    desc: 'Nuanțe milky & nude pentru un look curat, minimalist, elegant.',
    duration: 60,
    durationLabel: '1 h',
    price: 200,
    priceLabel: '200',
  },
  {
    id: 'oja-culoare',
    category: 'oja',
    index: '02',
    title: 'Ojă semipermanentă — culoare / model',
    shortTitle: 'Ojă semipermanentă (culoare/model)',
    desc: 'Culori vii sau modele delicate — alegerea este a ta, execuția este impecabilă.',
    duration: 90,
    durationLabel: '1 h 30 min',
    price: 230,
    priceLabel: '230',
    featured: true,
    badge: 'Popular',
  },
  {
    id: 'intr-12',
    category: 'gel',
    index: '03',
    title: 'Întreținere gel · mărimea 1–2',
    shortTitle: 'Întreținere gel 1–2',
    desc: 'Refill atent pentru unghii scurte — forma revine perfectă și lucioasă.',
    duration: 120,
    durationLabel: '2 h',
    price: 260,
    priceLabel: '260',
  },
  {
    id: 'intr-34',
    category: 'gel',
    index: '04',
    title: 'Întreținere gel · mărimea 3–4',
    shortTitle: 'Întreținere gel 3–4',
    desc: 'Refill complet pentru lungimi medii — echilibru între eleganță și durabilitate.',
    duration: 150,
    durationLabel: '2 h 30 min',
    price: 300,
    priceLabel: '300',
  },
  {
    id: 'intr-57',
    category: 'gel',
    index: '05',
    title: 'Întreținere / Construcție · mărimea 5–7',
    shortTitle: 'Întreținere/Construcție 5–7',
    desc: 'Lungimi statement — construcție robustă și design de efect.',
    duration: 210,
    durationLabel: '3 h 30 min',
    price: 400,
    priceLabel: '400',
  },
  {
    id: 'con-12',
    category: 'gel',
    index: '06',
    title: 'Construcție gel · mărimea 1–2',
    shortTitle: 'Construcție gel 1–2',
    desc: 'Bază solidă, discretă — perfectă pentru primul tău set.',
    duration: 150,
    durationLabel: '2 h 30 min',
    price: 310,
    priceLabel: '310',
  },
  {
    id: 'con-34',
    category: 'gel',
    index: '07',
    title: 'Construcție gel · mărimea 3–4',
    shortTitle: 'Construcție gel 3–4',
    desc: 'Forma ideală, finisaj cu oglindă — un set versatil pentru orice ocazie.',
    duration: 180,
    durationLabel: '3 h',
    price: 350,
    priceLabel: '350',
  },
  {
    id: 'design-3d',
    category: 'extra',
    index: '08',
    title: 'Design 3D — toate unghiile',
    shortTitle: 'Design 3D (toate unghiile)',
    desc: 'Texturi, pigmenți și picturi 3D care transformă fiecare unghie într-o piesă unică.',
    duration: 60,
    durationLabel: '1 h',
    price: 150,
    priceLabel: '100–200',
    accent: true,
    badge: 'Artistic',
    badgeDark: true,
    note: 'Extra — se adaugă peste manichiură',
  },
  {
    id: 'pictat',
    category: 'extra',
    index: '09',
    title: 'Model pictat — toate unghiile',
    shortTitle: 'Model pictat (toate unghiile)',
    desc: 'Modele pictate manual, pigmenți fini, dantelării și linii elegante.',
    duration: 30,
    durationLabel: '30 min',
    price: 100,
    priceLabel: '100',
    note: 'Extra — se adaugă peste întreținere',
  },
  {
    id: 'french-glass',
    category: 'extra',
    index: '10',
    title: 'French Glass',
    shortTitle: 'French Glass',
    desc: 'Finisajul cu efect de sticlă — strălucire subtilă, extrem de rafinată.',
    duration: 60,
    durationLabel: '1 h',
    price: 150,
    priceLabel: '150',
    note: 'Extra — se adaugă peste manichiură',
  },
  {
    id: 'demontare',
    category: 'extra',
    index: '11',
    title: 'Demontare',
    shortTitle: 'Demontare',
    desc: 'Curățare material tehnic, stilizare cuticulă și tratament pentru regenerare.',
    duration: 45,
    durationLabel: '45 min',
    price: 80,
    priceLabel: '80',
  },
];
